# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mVeBcmVkNVFiREVic1gIXEMbXw1dEXrG
"""

!pip install flask-ngrok

from flask import Flask
import os
app = Flask(__name__)
@app.route("/")
def starting():
    return"""
    <html>
      <body style = "font-family: Arial;font-size: 20px; text-align: center; background-color: #CCC0C6;">
      <h1>Welcome to my page</h1>
        <p>Emmanouil Pyrovolakis, Mathematics</p>
        <hr>
        <a href="/education">Σπουδές/Education -> </a> <br><br>
        <a href="/workexperience">Εργασία/Work Experience -></a>
      </body>
    </html>
    """
@app.route("/education")
def education():
  return"""
  <html>
    <body style = "font-family: Arial;font-size: 24px; text-align: center; background-color: #CCC0C6;">
      <h1>Education</h1>
      <a href="/"> <- Πίσω στην Αρχική</a><br><br>
      <p>-> University of Crete<br>
      Bachelor of Science, Mathematics<br>
      2022-2026<br>
      Grade: 7.57/10<br><br><br><br><br>
      ->1st High School of Souda<br>
      Greek<br>
      2019-2022<br>
      Grade: 19.1/20
    </body>
  </html>
  """

@app.route("/workexperience")
def workexperience():
  return"""
  <html>
    <body style = "font-family: Arial;font-size: 18px; text-align: center; background-color: #CCC0C6;">
      <h1>Work Experience</h1>
      <a href="/"> <- Πίσω στην Αρχική</a><br><br>
      <p>-> Mathematics Tutor<br>
      2024-2026<br>
      Experienced in teaching both high school and univeristy students, breaking down complex mathematical problems into clear, manageable steps. Skilled at adapting explanations to different learning styles and academic levels. Supportive and patient communicator, committed to ensuring full understanding by providing thorough and repeated clarification when needed<br><br><br>
      ->Head Waiter<br>
      2023-2025 (Seasonal)<br>
      Aktaion Resataurant<br>
      Led service operations during high-demand seasons in a fast paced enviroment.Cordinated team workflow and ensured efficient table management and customer satisfaction. Handled guest requests and resolved issues with professionalism and composure. Developed leadership, decision making and multitasking skills under pressure<br><br><br>
      -> Barista/Waiter<br>
      2021-2023 (Seasonal)<br>
      Delizia Gelato Italiano<br>
      Worked in high-demand peak tourist seasons from the outset, consistently delivering high quality customer service in fast-paced and competitive enviroments. Demonstrated adaptability, efficiency and professionalism while managing multiple tasks and maintaining strong attention to detail
    </body>
  </html>
  """

if __name__ == "__main__":
    # Αυτό το κομμάτι είναι απαραίτητο για να παίξει στο Render
    port = int(os.environ.get("PORT", 5000))
    app.run(host='0.0.0.0', port=port)